### PR TITLE
Updated Dockerfile and package.json

### PR DESCRIPTION
**Pull request by alecghica**

### CODE REVIEW

**Comment by nileshgulia1** [comment]
@valentinab25 Why automated release to 2.8.x?

**Comment by valentinab25** [comment]
> 
> 
> @valentinab25 Why automated release to 2.8.x?

Last release was 2.7.0-beta.xx, rancher does not know semantic versioning, but uses alphabetic sort, so you need a bigger version to upgrade the stack ( 2.7.0 is not bigger than 2.7.0-beta.xx for rancher)

**Comment by nileshgulia1** [comment]
@valentinab25 That's true , but this way we skip the versions right?
Can we disable automated release for projects?

**Comment by nileshgulia1** [comment]
Screenshot 2021-09-27 at 6 02 14 PM
It also leads to confusion among developers.

**Review by nileshgulia1 — APPROVED** [review]

**Pull request merged**
